// File: Jenkinsfile
pipeline {
    agent any

    tools {
        // IMPORTANT: Replace 'M3' and 'JDK 17' with the names configured in 
        // Manage Jenkins -> Tools -> Maven & JDK installations
        maven 'M3' 
        jdk 'JDK 17' 
    }

    stages {
        stage('Checkout') {
            steps {
                echo 'Pulling latest code from SCM...'
                // The Git plugin handles the actual checkout based on job configuration
            }
        }

        stage('Build with Maven') {
            steps {
                // Execute Maven command to compile, test, and package the WAR file
                sh "mvn clean package" 
                // Archive the WAR file for backup/traceability (optional)
                archiveArtifacts artifacts: 'target/*.war', onlyIfSuccessful: true
            }
        }

        stage('Deploy to Tomcat') {
            steps {
                // Uses the "Deploy to container" Jenkins Plugin
                deploy adapters: [
                    tomcat90(
                        // IMPORTANT: Replace 'tomcat-manager-creds' with the ID of 
                        // your Username/Password credential in Jenkins
                        credentialsId: 'tomcat-manager-creds', 
                        // IMPORTANT: Update with your Tomcat Manager URL
                        url: 'http://<tomcat-server-ip>:8080/manager/text' 
                    )
                ], 
                // Targets the WAR file generated by Maven
                war: 'target/*.war' 
            }
        }
    }
}
